# Uncomment this line to define a global platform for your project
platform :ios, ‘8.0’
target ‘frameWork’ do

pod 'AFNetworking', '~> 3.0.4'
pod 'SBJson', '~> 4.0.2'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'MJRefresh', '~> 3.1.0'
pod 'MJExtension', '~> 3.0.10'
pod 'Mantle', '~> 2.0.6'
pod 'FMDB', '~> 2.6'
pod 'MTLFMDBAdapter', '~> 0.2.0'
pod 'Masonry', '~> 0.6.4'
pod 'IQKeyboardManager'

end